### ISSUE TITLE
sd_mmc.c schizophrenic about SD_MMC_SPI_MEM_CNT

### ISSUE THREAD

**Issue by dnewman-polar3d** [dc42/CoreNG#1]
Near the start of sd_mmc.c, the code honors SD_MMC_SPI_MEM_CNT and handles the case where it is 0.  However, later on in the code -- in sd_mmc_init() -- it attempts to use &spiInterface even though it is not defined when SD_MMC_SPI_MEM_CNT is zero.  One simple workaround might be

        {
    #if (SD_MMC_SPI_MEM_CNT != 0)
            card->iface = &spiInterface;
            card->slot = slot - SD_MMC_HSMCI_MEM_CNT;
    #endif
        }

**Comment by dc42** [comment]
Fixed in 1.19beta11+2.
